services:
  - type: web
    name: find-jobs-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PYROGRAM_API_ID
        sync: false
      - key: PYROGRAM_API_HASH
        sync: false
      - key: JOB_SCRAPE_INTERVAL_MINUTES
        sync: false   